---
title: "Quick data analysis"
author: "The R Lobby"
date: "2025-12-09"
output: 
  pdf_document:
    toc: true
    toc_depth: 4
    number_sections: true
    keep_tex: true
abstract: |
  | This document quickly presents some code to export tables and figures in the case of collaborative work with Github and Overleaf integration.
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F, message=F)

#We clear the environment 
rm(list=ls())

#Useful libraries
library(dplyr)
library(readr)
library(xtable) #To format tables and export them in .tex format
library(kableExtra) #To visualise tables in a PDF document
library(readxl) # To import xls files
library(haven) #To import .dta files
library(here) #To correctly set the working directory
library(reshape2) #To modify dataframes
library(stringr) #To substract strings
library(collapse) #For fast data transformation
library(ggplot2) #For figures
library(cowplot) #For multiple figures
library(gtable)
library(grid)
library(ggtext)
library(tidyverse)
library(fixest)
library(texreg)

#Data import
members_fun <- read_csv(file = here("data_out", "dial_members_fun.csv"))

#Set some interesting paths
fig_dir <- here::here("paper_presentation", "figures")
tab_dir <- here::here("paper_presentation", "tables")

```

\newpage

# Descriptive statistics

Here are some basic descriptive statistics about our sample with a stupid figure.

```{r fig-meetings-satisfaction, fig.align='center', fig.cap="More meetings, more satisfaction ?", fig.height=5, fig.show='hold', fig.width=11, message=FALSE, warning=FALSE, results='asis'}

#Prepare the plot
fig_meetings_satisfaction <- ggplot(members_fun, aes(x = meetings_month, y = life_satisfaction)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title    = "More meetings, more satisfaction ?",
    x        = "Number of meetings/month",
    y        = "Life Satisfaction(1–10)",
    caption  = "Fictious data"
  )

#Display the plot
fig_meetings_satisfaction

#Save the plot
ggsave(filename = "meetings_satisfaction.png", plot = fig_meetings_satisfaction, path = fig_dir, limitsize=FALSE, width = 11, height = 5)

```


And a stupid table 

```{r stupid-descriptive-statistics-table}
#List of variables
vars <- c(
  "coffee_cups_week",
  "git_commits",
  "overleaf_projects",
  "meetings_month",
  "has_cat",
  "life_satisfaction"
)

#Generate the descriptive statistics table 
desc_table <- members_fun %>%
  summarise( across(all_of(vars),
             list(
               n = ~sum(!is.na(.)),
               mean = ~mean(., na.rm = TRUE),
               sd = ~sd(., na.rm = TRUE),
               min = ~min(., na.rm = TRUE), 
               max = ~max(., na.rm = TRUE)),
             .names = "{.col}_{.fn}"),
            .groups = "drop") %>%
              pivot_longer(
                everything(),
                names_to = c("variable", "stat"),
                # REGEX: capture everything before last "_" and everything after
                names_pattern = "(.+)_(n|mean|sd|min|max)$",
                values_to = "value") %>%
              pivot_wider(
                names_from = stat,
                values_from = value)

desc_table$variable <- c(
  "Coffee cups/week",
  "Nb. Git commits",
  "Nb. Overleaf projects",
  "Nb. Meetings/month",
  "Has a cat",
  "Life satisfaction Index (1-10)"
)

#Kable 
k_desc_table <- kable(desc_table,
                       linesep = "",
                      digits = 1, 
                      align = c("l","c", "c", "c", "c", "c"),
                      caption = "\\label{tab:desc-stats}Descriptive statistics of the sample of DIAL PhD Candidates",
                      format = "latex",
                      booktabs = TRUE,
                      col.names = c("Variable","Nb. Obs", "Mean", "SD", "Min", "Max"),
                      row.names = F, 
                      escape = F) %>%
 kable_styling(latex_options = c("hold_position", font_size = 6)) %>%
  row_spec(0, bold = F) %>%
  add_header_above(c(" ", "I" = 1, "can add"= 2, "stuff above" = 2)) %>%
  pack_rows("And create", 1, 2) %>%
  pack_rows("some random", 3, 4) %>%
  pack_rows("groupings", 5, 6) %>%
  footnote(general = "Source is bullshit extracted from the DIAL-IRD website on December 2025. Authors' calculations.", general_title = "Notes:", threeparttable = T,  footnote_as_chunk = T)

#Save as .tex format
writeLines(k_desc_table, paste(tab_dir,"desc_stats.tex", sep = "/"))

#Present the table in the pdf to keep track
k_desc_table

```


\newpage
# Simple analysis example

And here is a stupid analysis :

```{r stupid-regression, results='asis', message=F, warning=F}
#Deux models
model_1 <- feols(life_satisfaction ~ i(as.factor(status), ref = "Doctorant") + coffee_cups_week + i(as.factor(has_cat)), data = members_fun, cluster = ~axis)

model_2 <- feols(life_satisfaction ~ i(as.factor(status), ref = "Doctorant") + coffee_cups_week + i(as.factor(has_cat)) + i(axis), data = members_fun, cluster = ~axis)

#Test 2

#List of models 
list_models <- list(model_1, model_2)

#Mean doctorants
mean_doctorants <- mean(members_fun$life_satisfaction[members_fun$status=="Doctorant"], na.rm = T)

#Tableau texreg
stupidreg <- texreg(list_models, 
       digits = 2,
       stars = c(0.1, 0.05, 0.01),
       caption = "Stupid regression examples",
       caption.above = TRUE,
       custom.coef.map = list("as.factor(status)::Doctorante" = "Doctorante", "as.factor(status)::Post-doc"="Post-Doc", "coffee_cups_week"="Nb. Coffee cups/week", "as.factor(has_cat)::1"="Has a cat"),
       custom.model.names = c("Model 1",
                              "Model 2"
                              ),
       gof.ignore = c("R2 (proj model)", "Adj.R2 (proj model)", "R^2", "Adj. R^2"),
       custom.gof.rows = list("Research Axis FE" = c("Non", "Oui"),
                              "Moy. Doctorants" = c(mean_doctorants, mean_doctorants)),
       # # custom.header = list(
       #   "\\textbf{Engagement éducation}" = 1:3,
       #   "\\textbf{Citoyenneté}" = 4:6,
       #   "\\textbf{Intégration}" = 7:10),
       custom.note = paste0("Cluster au niveau des thèmes de recherche"),
       scalebox = 0.6,
       use.packages = FALSE,
       booktabs = TRUE,
       float.pos = "h")

#Save as .tex format
writeLines(stupidreg, paste(tab_dir,"stupidreg.tex", sep = "/"))

#Present the table in the pdf to keep track
stupidreg

```

